# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rpc_pb2 as rpc__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RouteGuideStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/routeguide.RouteGuide/add',
                request_serializer=rpc__pb2.addMsg.SerializeToString,
                response_deserializer=rpc__pb2.addReply.FromString,
                _registered_method=True)
        self.rawImage = channel.unary_unary(
                '/routeguide.RouteGuide/rawImage',
                request_serializer=rpc__pb2.rawImageMsg.SerializeToString,
                response_deserializer=rpc__pb2.imageReply.FromString,
                _registered_method=True)
        self.dotProduct = channel.unary_unary(
                '/routeguide.RouteGuide/dotProduct',
                request_serializer=rpc__pb2.dotProductMsg.SerializeToString,
                response_deserializer=rpc__pb2.dotProductReply.FromString,
                _registered_method=True)
        self.jsonImage = channel.unary_unary(
                '/routeguide.RouteGuide/jsonImage',
                request_serializer=rpc__pb2.jsonImageMsg.SerializeToString,
                response_deserializer=rpc__pb2.imageReply.FromString,
                _registered_method=True)


class RouteGuideServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rawImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dotProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def jsonImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteGuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=rpc__pb2.addMsg.FromString,
                    response_serializer=rpc__pb2.addReply.SerializeToString,
            ),
            'rawImage': grpc.unary_unary_rpc_method_handler(
                    servicer.rawImage,
                    request_deserializer=rpc__pb2.rawImageMsg.FromString,
                    response_serializer=rpc__pb2.imageReply.SerializeToString,
            ),
            'dotProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.dotProduct,
                    request_deserializer=rpc__pb2.dotProductMsg.FromString,
                    response_serializer=rpc__pb2.dotProductReply.SerializeToString,
            ),
            'jsonImage': grpc.unary_unary_rpc_method_handler(
                    servicer.jsonImage,
                    request_deserializer=rpc__pb2.jsonImageMsg.FromString,
                    response_serializer=rpc__pb2.imageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routeguide.RouteGuide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('routeguide.RouteGuide', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouteGuide(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routeguide.RouteGuide/add',
            rpc__pb2.addMsg.SerializeToString,
            rpc__pb2.addReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def rawImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routeguide.RouteGuide/rawImage',
            rpc__pb2.rawImageMsg.SerializeToString,
            rpc__pb2.imageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dotProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routeguide.RouteGuide/dotProduct',
            rpc__pb2.dotProductMsg.SerializeToString,
            rpc__pb2.dotProductReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def jsonImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routeguide.RouteGuide/jsonImage',
            rpc__pb2.jsonImageMsg.SerializeToString,
            rpc__pb2.imageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
