# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\nrouteguide\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\x87\x02\n\nRouteGuide\x12\x31\n\x03\x61\x64\x64\x12\x12.routeguide.addMsg\x1a\x14.routeguide.addReply\"\x00\x12=\n\x08rawImage\x12\x17.routeguide.rawImageMsg\x1a\x16.routeguide.imageReply\"\x00\x12\x46\n\ndotProduct\x12\x19.routeguide.dotProductMsg\x1a\x1b.routeguide.dotProductReply\"\x00\x12?\n\tjsonImage\x12\x18.routeguide.jsonImageMsg\x1a\x16.routeguide.imageReply\"\x00\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'
  _globals['_ADDMSG']._serialized_start=25
  _globals['_ADDMSG']._serialized_end=55
  _globals['_RAWIMAGEMSG']._serialized_start=57
  _globals['_RAWIMAGEMSG']._serialized_end=83
  _globals['_DOTPRODUCTMSG']._serialized_start=85
  _globals['_DOTPRODUCTMSG']._serialized_end=122
  _globals['_JSONIMAGEMSG']._serialized_start=124
  _globals['_JSONIMAGEMSG']._serialized_end=151
  _globals['_ADDREPLY']._serialized_start=153
  _globals['_ADDREPLY']._serialized_end=176
  _globals['_DOTPRODUCTREPLY']._serialized_start=178
  _globals['_DOTPRODUCTREPLY']._serialized_end=215
  _globals['_IMAGEREPLY']._serialized_start=217
  _globals['_IMAGEREPLY']._serialized_end=260
  _globals['_ROUTEGUIDE']._serialized_start=263
  _globals['_ROUTEGUIDE']._serialized_end=526
# @@protoc_insertion_point(module_scope)
